### Q-4. Imagine you working as a sale manager now you need to predict the Revenue and whether that particular revenue is on the weekend or not and find the Informational_Duration using the Ensemble learning algorithm

In [49]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model  import Ridge,Lasso,RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LogisticRegression
from sklearn.model_selection import train_test_split,RandomizedSearchCV
from statsmodels.stats.outliers_influence import variance_inflation_factor 
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score
%matplotlib inline

In [39]:
data = pd.read_csv('online_shoppers_intention.csv')
data.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                     0.0               1                 0.000000   
1                     0.0               2                64.000000   
2                     0.0               1                 0.000000   
3                     0.0               2                 2.666667   
4                     0.0              10               627.500000   

   BounceRates  ExitRates  PageValues  SpecialDay Month  OperatingSystems  \
0         0.20       0.20         0.0         0.0   Feb                 1   
1         0.00       0.10         0.0         0.0   Feb                 2   
2         0.20       0.20         0.0         0.0   Feb                 4   
3         0.05       0.14         0.0         0.0   Feb                 3   
4         0.02       0.05         0.0         0.0   Feb                 3   

   Browser  Region  TrafficType        VisitorType  Weekend  Revenue  
0        1       1            1  Returning_Visitor    False    False  
1        2       1            2  Returning_Visitor    False    False  
2        1       9            3  Returning_Visitor    False    False  
3        2       2            4  Returning_Visitor    False    False  
4        3       1            4  Returning_Visitor     True    False

In [40]:
data.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay', 'Month',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType',
       'Weekend', 'Revenue'],
      dtype='object')

In [41]:
data.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

### Drop unnecessary feature

In [42]:
data = data.drop(['BounceRates', 'ExitRates', 'SpecialDay',  'OperatingSystems', 'Browser', 'VisitorType', 'Month', 'Region', 'TrafficType', 'Weekend'], axis = 1)

In [43]:
data.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'PageValues', 'Revenue'],
      dtype='object')

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data['Revenue'] = le.fit_transform(data['Revenue'])

In [45]:
data

Administrative  Administrative_Duration  Informational  \
0                   0                      0.0              0   
1                   0                      0.0              0   
2                   0                      0.0              0   
3                   0                      0.0              0   
4                   0                      0.0              0   
...               ...                      ...            ...   
12325               3                    145.0              0   
12326               0                      0.0              0   
12327               0                      0.0              0   
12328               4                     75.0              0   
12329               0                      0.0              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                         0.0               1                 0.000000   
1                         0.0               2                64.000000   
2                         0.0               1                 0.000000   
3                         0.0               2                 2.666667   
4                         0.0              10               627.500000   
...                       ...             ...                      ...   
12325                     0.0              53              1783.791667   
12326                     0.0               5               465.750000   
12327                     0.0               6               184.250000   
12328                     0.0              15               346.000000   
12329                     0.0               3                21.250000   

       PageValues  Revenue  
0        0.000000        0  
1        0.000000        0  
2        0.000000        0  
3        0.000000        0  
4        0.000000        0  
...           ...      ...  
12325   12.241717        0  
12326    0.000000        0  
12327    0.000000        0  
12328    0.000000        0  
12329    0.000000        0  

[12330 rows x 8 columns]

In [46]:
X = data.drop("Revenue",axis=1)
X.head()

Administrative  Administrative_Duration  Informational  \
0               0                      0.0              0   
1               0                      0.0              0   
2               0                      0.0              0   
3               0                      0.0              0   
4               0                      0.0              0   

   Informational_Duration  ProductRelated  ProductRelated_Duration  PageValues  
0                     0.0               1                 0.000000         0.0  
1                     0.0               2                64.000000         0.0  
2                     0.0               1                 0.000000         0.0  
3                     0.0               2                 2.666667         0.0  
4                     0.0              10               627.500000         0.0

In [47]:
y = data["Revenue"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Revenue, dtype: int64

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [51]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [52]:
X_train_tf = scaler.transform(X_train)
X_train_tf

array([[ 0.51433196,  0.96414162, -0.39758668, ..., -0.46488398,
        -0.42361972, -0.3157467 ],
       [ 4.16380269,  1.33632531,  4.27005461, ...,  3.15871081,
         2.73700807, -0.3157467 ],
       [-0.70215829, -0.46414825, -0.39758668, ..., -0.48725185,
        -0.51079798, -0.3157467 ],
       ...,
       [-0.70215829, -0.46414825, -0.39758668, ..., -0.64382693,
        -0.54761861, -0.3157467 ],
       [-0.70215829, -0.46414825, -0.39758668, ..., -0.42014824,
        -0.48480695, -0.3157467 ],
       [ 1.42669964,  0.32512473, -0.39758668, ..., -0.50961972,
        -0.52416712, -0.3157467 ]])

In [60]:
X_test_tf = scaler.transform(X_test)
X_test_tf

array([[ 0.2102094 ,  0.34997698, -0.39758668, ...,  0.36272718,
        -0.08018288, -0.3157467 ],
       [ 1.12257708,  2.03473802,  1.15829375, ...,  1.14560259,
         0.70584332, -0.20493049],
       [-0.39803573, -0.22919456, -0.39758668, ...,  2.10742096,
         1.68382254, -0.1324319 ],
       ...,
       [-0.39803573, -0.22133897,  0.38035353, ...,  1.61532784,
         1.54561049,  7.19830629],
       [ 2.03494476, -0.09184069, -0.39758668, ...,  2.04031736,
         2.5824455 ,  0.25221346],
       [-0.70215829, -0.46414825, -0.39758668, ..., -0.48725185,
        -0.53917153, -0.3157467 ]])

### XGBClassifier

In [90]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train_tf, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [91]:
classifier.score(X_train_tf,y_train)

0.9713109793003268

In [92]:
y_pred_xgb = classifier.predict(X_test_tf)
accuracy_score(y_test, y_pred_xgb)

0.8859670680756943

In [93]:
cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

[[3269  167]
 [ 297  336]]


In [94]:
print("XGBoost Classifier report: \n\n", classification_report(y_test, y_pred_xgb))

XGBoost Classifier report: 

               precision    recall  f1-score   support

           0       0.92      0.95      0.93      3436
           1       0.67      0.53      0.59       633

    accuracy                           0.89      4069
   macro avg       0.79      0.74      0.76      4069
weighted avg       0.88      0.89      0.88      4069



### Random Forest Classifier

In [70]:
classifier_rf = RandomForestClassifier()
classifier_rf.fit(X_train_tf, y_train)

RandomForestClassifier()

In [71]:
classifier_rf.score(X_train_tf,y_train)

0.9997578985594965

In [72]:
y_pred_rf = classifier_rf.predict(X_test_tf)
accuracy_score(y_test, y_pred_rf)

0.8849840255591054

In [89]:
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[3270  166]
 [ 302  331]]


In [95]:
print("Random Forest Classifier report: \n\n", classification_report(y_test, y_pred_rf))

Random Forest Classifier report: 

               precision    recall  f1-score   support

           0       0.92      0.95      0.93      3436
           1       0.67      0.52      0.59       633

    accuracy                           0.88      4069
   macro avg       0.79      0.74      0.76      4069
weighted avg       0.88      0.88      0.88      4069



### DecisionTreeClassifier

In [73]:
classifier_dt = DecisionTreeClassifier()
classifier_dt.fit(X_train_tf, y_train)

DecisionTreeClassifier()

In [74]:
classifier_dt.score(X_train_tf,y_train)

0.9997578985594965

In [75]:
y_pred_dt = classifier_dt.predict(X_test_tf)
accuracy_score(y_test, y_pred_dt)

0.8493487343327599

In [88]:
cm = confusion_matrix(y_test, y_pred_dt)
print(cm)

[[3315  121]
 [ 308  325]]


In [96]:
print("Decision Tree Classifier report: \n\n", classification_report(y_test, y_pred_dt))

Decision Tree Classifier report: 

               precision    recall  f1-score   support

           0       0.91      0.96      0.94      3436
           1       0.73      0.51      0.60       633

    accuracy                           0.89      4069
   macro avg       0.82      0.74      0.77      4069
weighted avg       0.89      0.89      0.89      4069



### GuassianNB

In [76]:
from sklearn.naive_bayes import GaussianNB
classifier_gnb = GaussianNB()
classifier_gnb.fit(X_train_tf, y_train)

GaussianNB()

In [77]:
classifier_gnb.score(X_train_tf,y_train)

0.8495339547270306

In [84]:
y_pred_gnb = classifier_gnb.predict(X_test_tf)
accuracy_score(y_test, y_pred_gnb)

0.8510690587367904

In [87]:
cm = confusion_matrix(y_test, y_pred_gnb)
print(cm)

[[3173  263]
 [ 343  290]]


In [97]:
print("GaussianNB Classifier report: \n\n", classification_report(y_test, y_pred_gnb))

GaussianNB Classifier report: 

               precision    recall  f1-score   support

           0       0.90      0.92      0.91      3436
           1       0.52      0.46      0.49       633

    accuracy                           0.85      4069
   macro avg       0.71      0.69      0.70      4069
weighted avg       0.84      0.85      0.85      4069



### Support Vector Classifier

In [80]:
classifier_svc = SVC(kernel = 'rbf', random_state = 0)
classifier_svc.fit(X_train_tf, y_train)

SVC(random_state=0)

In [81]:
classifier_svc.score(X_train_tf,y_train)

0.9023120687568091

In [83]:
y_pred_svc = classifier_svc.predict(X_test_tf)
accuracy_score(y_test, y_pred_svc)

0.8945686900958466

In [86]:
cm = confusion_matrix(y_test, y_pred_svc)
print(cm)

[[3315  121]
 [ 308  325]]


In [98]:
print("Support Vector Classifier report: \n\n", classification_report(y_test, y_pred_svc))

Support Vector Classifier report: 

               precision    recall  f1-score   support

           0       0.91      0.96      0.94      3436
           1       0.73      0.51      0.60       633

    accuracy                           0.89      4069
   macro avg       0.82      0.74      0.77      4069
weighted avg       0.89      0.89      0.89      4069



### KNeighborsClassifier

In [99]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knb = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knb.fit(X_train_tf, y_train)

KNeighborsClassifier()

In [100]:
classifier_knb.score(X_train_tf,y_train)

0.9135697857402252

In [101]:
y_pred_knb = classifier_knb.predict(X_test_tf)
accuracy_score(y_test, y_pred_knb)

0.8835094617842222

In [102]:
cm = confusion_matrix(y_test, y_pred_knb)
print(cm)

[[3289  147]
 [ 327  306]]


In [103]:
print("Kneighbors Classifier report: \n\n", classification_report(y_test, y_pred_knb))

Kneighbors Classifier report: 

               precision    recall  f1-score   support

           0       0.91      0.96      0.93      3436
           1       0.68      0.48      0.56       633

    accuracy                           0.88      4069
   macro avg       0.79      0.72      0.75      4069
weighted avg       0.87      0.88      0.88      4069



### Logistic Regression

In [104]:
classifier_lgr = LogisticRegression()
classifier_lgr.fit(X_train, y_train)

LogisticRegression()

In [105]:
classifier_lgr.score(X_train_tf,y_train)

0.8456603316789735

In [106]:
y_pred_lgr = classifier_lgr.predict(X_test_tf)
accuracy_score(y_test, y_pred_lgr)

0.8444335217498157

In [108]:
cm = confusion_matrix(y_test, y_pred_lgr)
print(cm)

[[3436    0]
 [ 633    0]]


In [107]:
print("Logistic Regressin report: \n\n", classification_report(y_test, y_pred_lgr))

Logistic Regressin report: 

               precision    recall  f1-score   support

           0       0.84      1.00      0.92      3436
           1       0.00      0.00      0.00       633

    accuracy                           0.84      4069
   macro avg       0.42      0.50      0.46      4069
weighted avg       0.71      0.84      0.77      4069

